apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: datum-net
data:
  POSTGRES_DB: datum_astro
  POSTGRES_USER: datum_astro
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: datum-net
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: datum-net
  labels:
    app: postgres
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: datum-net
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  hostPath:
    path: /data/postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: datum-net
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
  volumeName: postgres-pv
