apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
              name: postgres-secret
          volumeMounts:
            - name: postgres_data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres_data
          persistentVolumeClaim:
            claimName: postgres-volume
