apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: datum
  labels:
    app: postgres
data:
  POSTGRES_PASSWORD: YXN0cm9fZGJfcGFzc3dvcmQ= # base64-encoded value of "astro_db_password"
