apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
data:
  POSTGRES_DB: YXN0cm9fZGJfbmFtZQ==  # base64-encoded value of "astro_db_name"
  POSTGRES_USER: YXN0cm9fZGJfdXNlcg==  # base64-encoded value of "astro_db_user"
  POSTGRES_PASSWORD: YXN0cm9fZGJfcGFzc3dvcmQ=  # base64-encoded value of "astro_db_password"
