apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datum-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: datum-pv
