apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: datum-net
addressType: FQDN
ports:
  - name: https
    protocol: TCP
    appProtocol: https
    port: 443
endpoints:
  - addresses:
      - "website.prod.env.datum.net"
    conditions:
      ready: true
