services:
  dev:
    build:
      context: .
      target: development
      args:
        - SITE_URL=${SITE_URL}
        - API_URL=${API_URL}
        - SITE_GITHUB=${SITE_GITHUB}
        - APP_PRIVATE_KEY=${APP_PRIVATE_KEY}
        - APP_INSTALLATION_ID=${APP_INSTALLATION_ID}
        - APP_ID=${APP_ID}
        - ASTRO_DB_APP_TOKEN=${ASTRO_DB_APP_TOKEN}
        - ASTRO_STUDIO_APP_TOKEN=${ASTRO_STUDIO_APP_TOKEN}
        - ASTRO_DB_REMOTE_URL=${ASTRO_DB_REMOTE_URL}
        - ASTRO_TELEMETRY_DISABLED=${ASTRO_TELEMETRY_DISABLED}
    ports:
      - '4321:4321'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    networks:
      - datum-network
    command: npm run dev -- --host 0.0.0.0 --port 4321

  prod:
    build:
      context: .
      target: production
      args:
        - SITE_URL=${SITE_URL}
        - API_URL=${API_URL}
        - SITE_GITHUB=${SITE_GITHUB}
        - APP_PRIVATE_KEY=${APP_PRIVATE_KEY}
        - APP_INSTALLATION_ID=${APP_INSTALLATION_ID}
        - APP_ID=${APP_ID}
        - ASTRO_DB_APP_TOKEN=${ASTRO_DB_APP_TOKEN}
        - ASTRO_STUDIO_APP_TOKEN=${ASTRO_STUDIO_APP_TOKEN}
        - ASTRO_DB_REMOTE_URL=${ASTRO_DB_REMOTE_URL}
        - ASTRO_TELEMETRY_DISABLED=${ASTRO_TELEMETRY_DISABLED}
    ports:
      - '4321:4321'
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=4321
    env_file:
      - .env
    restart: unless-stopped

networks:
  datum-network:
    driver: bridge
