services:
  dev:
    build:
      context: .
      target: development
    ports:
      - '4321:4321'
    volumes:
      - .:/app
      - /app/node_modules
      - persistent-data:/app/.persistent
    environment:
      - NODE_ENV=development
      - GH_ACCESS_TOKEN=${GH_ACCESS_TOKEN}
    env_file:
      - .env
    networks:
      - datum-network
    command: npm run dev -- --host 0.0.0.0 --port 4321

  prod:
    build:
      context: .
      target: production
    ports:
      - '4321:4321'
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=4321
      - GH_ACCESS_TOKEN=${GH_ACCESS_TOKEN}
    networks:
      - datum-network
    restart: unless-stopped

networks:
  datum-network:
    driver: bridge

volumes:
  persistent-data:
    driver: local
