services:
  dev:
    build:
      context: .
      target: development
    ports:
      - '4321:4321'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    networks:
      - datum-network
    command: npm run dev -- --host 0.0.0.0 --port 4321

  # Preview service for static site
  preview:
    build:
      context: .
      target: preview
    ports:
      - '4321:4321'
    environment:
      - NODE_ENV=production
      - SITE_URL=${SITE_URL}
    restart: unless-stopped
    networks:
      - datum-network

  # Production service using SSR
  prod:
    build:
      context: .
      target: production
    ports:
      - '4321:4321'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=4321
    restart: unless-stopped
    networks:
      - datum-network

networks:
  datum-network:
    driver: bridge
