{{- define "gvList" -}}
{{- $groupVersions := . -}}

---
title: API Reference
sidebar:
  order: 4
---

{/* AUTO-GENERATED FILE - DO NOT EDIT
  This file is generated by: npm run generate:api-docs
  To update: modify operator versions in .api-docs-config.yaml and regenerate
*/}

## Packages
{{- range $groupVersions }}
- {{ markdownRenderGVLink . }}
{{- end }}

{{ range $groupVersions }}
{{ template "gvDetails" . }}
{{ end }}

{{- end -}}
