{{- define "gvList" -}}
{{- $groupVersions := . -}}

---
title: API Reference
sidebar:
  order: 4
---

<!--
  WARNING: This file is auto-generated by `npm run generate:api-docs`
  Do not edit this file directly. Changes will be overwritten.

  To update this file:
  1. Modify operator versions in .api-docs-config.yaml
  2. Run `npm run generate:api-docs`

  Or wait for Renovate to automatically update operator versions.
-->

## Packages
{{- range $groupVersions }}
- {{ markdownRenderGVLink . }}
{{- end }}

{{ range $groupVersions }}
{{ template "gvDetails" . }}
{{ end }}

{{- end -}}
