import {
  ArrowRight,
  BookImage,
  BookOpen,
  BookText,
  CalendarRange,
  ChevronDown,
  CircleArrowRight,
  Cloud,
  Code,
  Command,
  Database,
  FileText,
  GitBranch,
  GitCommit,
  GitCompare,
  GitMerge,
  GitPullRequest,
  Github,
  Globe,
  Goal,
  Heart,
  Key,
  Linkedin,
  ListRestart,
  Lock,
  MessageSquarePlus,
  Network,
  Power,
  Server,
  Settings,
  Shield,
  Shirt,
  Slack,
  Star,
  Terminal,
  Twitter,
  User,
  Users,
  Webhook,
  Zap,
} from 'lucide-astro';

// Icon mapping object
const iconMap = {
  goal: Goal,
  users: Users,
  github: Github,
  user: User,
  'chevron-down': ChevronDown,
  'circle-arrow-right': CircleArrowRight,
  'book-open': BookOpen,
  'file-text': FileText,
  settings: Settings,
  globe: Globe,
  code: Code,
  heart: Heart,
  star: Star,
  zap: Zap,
  shield: Shield,
  lock: Lock,
  key: Key,
  database: Database,
  server: Server,
  network: Network,
  cloud: Cloud,
  terminal: Terminal,
  command: Command,
  'arrow-right': ArrowRight,
  'git-branch': GitBranch,
  'git-commit': GitCommit,
  'git-pull-request': GitPullRequest,
  'git-merge': GitMerge,
  'git-compare': GitCompare,
  power: Power,
  webhook: Webhook,
  'list-restart': ListRestart,
  'calendar-range': CalendarRange,
  shirt: Shirt,
  slack: Slack,
  'book-text': BookText,
  'book-image': BookImage,
  'message-square-plus': MessageSquarePlus,
  twitter: Twitter,
  linkedin: Linkedin,
} as const;

// Icon mapping function
export const getIcon = (iconName: string) => {
  return iconMap[iconName as keyof typeof iconMap] || null;
};

// Type for icon names
export type IconName = keyof typeof iconMap;
