import {
  ArrowRight,
  ArrowLeft,
  Backpack,
  Blend,
  BookImage,
  BookOpen,
  BookText,
  Lightbulb,
  Calendar,
  CalendarCheck2,
  CalendarDays,
  CalendarPlus,
  CalendarRange,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeftRightEllipsis,
  CircleArrowRight,
  CircleCheck,
  CircleGauge,
  CircleX,
  Clock,
  ClockFading,
  Cloud,
  Cloudy,
  Code,
  Command,
  Copy,
  Database,
  FileText,
  GitBranch,
  GitCommit,
  GitCompare,
  GitMerge,
  GitPullRequest,
  Github,
  Globe,
  Goal,
  Handshake,
  Heart,
  HeartHandshake,
  Image,
  IdCard,
  Info,
  Key,
  KeyRound,
  MapPin,
  MapPinHouse,
  House,
  Link,
  Linkedin,
  ListRestart,
  Lock,
  LockOpen,
  LogIn,
  Menu,
  MessagesSquare,
  MessageSquarePlus,
  Minus,
  Moon,
  Network,
  NotebookPen,
  Package,
  Paintbrush,
  Pencil,
  PencilLine,
  PiggyBank,
  Plus,
  Power,
  Presentation,
  ScanHeart,
  Search,
  Server,
  Settings,
  Shield,
  ShieldPlus,
  Shirt,
  Slack,
  Star,
  Sun,
  Terminal,
  TriangleAlert,
  Twitter,
  User,
  UserLock,
  Users,
  Video,
  Waypoints,
  Wallet,
  WalletMinimal,
  Webhook,
  X,
  Zap,
} from 'lucide-astro';

// Icon mapping object
const iconMap = {
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  backpack: Backpack,
  blend: Blend,
  'book-image': BookImage,
  'book-open': BookOpen,
  'book-text': BookText,
  bulb: Lightbulb,
  calendar: Calendar,
  'calendar-check-2': CalendarCheck2,
  'calendar-days': CalendarDays,
  'calendar-plus': CalendarPlus,
  'calendar-range': CalendarRange,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevrons-left-right-ellipsis': ChevronsLeftRightEllipsis,
  'circle-arrow-right': CircleArrowRight,
  'circle-check': CircleCheck,
  'circle-gauge': CircleGauge,
  'circle-x': CircleX,
  clock: Clock,
  'clock-fading': ClockFading,
  cloud: Cloud,
  cloudy: Cloudy,
  code: Code,
  command: Command,
  copy: Copy,
  database: Database,
  'file-text': FileText,
  'git-branch': GitBranch,
  'git-commit': GitCommit,
  'git-compare': GitCompare,
  'git-merge': GitMerge,
  'git-pull-request': GitPullRequest,
  github: Github,
  globe: Globe,
  goal: Goal,
  handshake: Handshake,
  heart: Heart,
  'heart-handshake': HeartHandshake,
  house: House,
  'id-card': IdCard,
  image: Image,
  info: Info,
  key: Key,
  'key-round': KeyRound,
  link: Link,
  linkedin: Linkedin,
  'list-restart': ListRestart,
  lock: Lock,
  'lock-open': LockOpen,
  'log-in': LogIn,
  'map-pin': MapPin,
  'map-pin-house': MapPinHouse,
  menu: Menu,
  'message-square-plus': MessageSquarePlus,
  'messages-square': MessagesSquare,
  minus: Minus,
  moon: Moon,
  network: Network,
  'notebook-pen': NotebookPen,
  package: Package,
  paintbrush: Paintbrush,
  pencil: Pencil,
  'pencil-line': PencilLine,
  'piggy-bank': PiggyBank,
  plus: Plus,
  power: Power,
  presentation: Presentation,
  'scan-heart': ScanHeart,
  search: Search,
  server: Server,
  settings: Settings,
  shield: Shield,
  'shield-plus': ShieldPlus,
  shirt: Shirt,
  slack: Slack,
  star: Star,
  sun: Sun,
  terminal: Terminal,
  'triangle-alert': TriangleAlert,
  twitter: Twitter,
  user: User,
  'user-lock': UserLock,
  users: Users,
  video: Video,
  waypoints: Waypoints,
  wallet: Wallet,
  'wallet-minimal': WalletMinimal,
  webhook: Webhook,
  x: X,
  zap: Zap,
} as const;

// Icon mapping function
export const getIcon = (iconName: string) => {
  return iconMap[iconName as keyof typeof iconMap] || null;
};

// Type for icon names
export type IconName = keyof typeof iconMap;
